### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by liamxg** [nxrunning/Tidytuesdays#8]
df%>%
  filter(between(real_cost, quantile(df$real_cost, 0.25) - 1.5* IQR(df$real_cost), 
                 quantile(df$real_cost, 0.75) + 1.5* IQR(df$real_cost)))%>%
  ggbetweenstats(x = tunnel_group, y = real_cost, type = "robust", k = 2, 
                 mean.point.args = list(size = 5, color = "darkblue"))+
  ylim(0, 15000)+
  labs(title = "Partially underground transit lines more costly than\ncompletely above-ground and underground lines",
       caption = "Source: TransitCosts.com | Visualisation: @nxrunning",
       x = "",
       y = "Cost (Millions of USD)")+
  scale_color_manual(values = c("#245023", "#342447", "#cc2517"))+
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        plot.subtitle = element_text(size = 8))

Scale for 'colour' is already present. Adding another scale for 'colour', which will replace the
existing scale.

**Comment by liamxg** [comment]
![image](https://user-images.githubusercontent.com/46078579/105948241-97591480-60a5-11eb-8383-1ab29d71950c.png)
 darkblue is not shown.

**Comment by nxrunning** [comment]
![Transitcosts](https://user-images.githubusercontent.com/52667147/106163042-b5b53200-61c3-11eb-9e86-7837e4e0095b.jpeg)

The wrong image might have been uploaded. If you run the code, you should see this graph as above

**Comment by liamxg** [comment]
thanks.
